### ISSUE TITLE
Support packaging many handlers into a ready made container

### ISSUE THREAD

**Issue by ripienaar** [choria-io/asyncjobs#43]
Given a `asyncjobs.yaml` with the following content:

```yaml
nats: AJC
queue: DEFAULT
name: github.com/ripienaar/handlers
asyncjobs: latest
tasks:
  - type: email:new
    package:  github.com/myco/email-handler/newEmail
```

If `github.com/myco/email-handler/newEmail` had a method `AsyncJobHandler()` that implements `HandlerFunc` we should be able to generate a stub go program that runs all these handlers with sane defaults and package it all into a docker container.
